package challenge

/*
 * DO NOT EDIT THIS FILE
 *
 */

import (
	"testing"

	"github.com/garyburd/redigo/redis"
)

var keyboard = "qwertyuiopasdfghjklzxcvbnm"

func TestUpdates(t *testing.T) {
	db := NewRedisDB("127.0.0.1:6379")
	if err := runUpdates(db, updates); err != nil {
		panic(err)
	}

	e := calcExpected()
	conn, err := redis.Dial("tcp", "127.0.0.1:6379")
	if err != nil {
		panic(err)
	}

	for k, v := range e {
		rk := keyPrefix + ":" + k
		rv, err := redis.Int(conn.Do("GET", rk))
		if err != nil {
			t.Log("Error for key "+rk, err)
			t.FailNow()
		}

		if v != rv {
			t.Logf("expected %v for key %s, got %v\n", v, k, rv)
			t.FailNow()
		}
	}
}

func calcExpected() map[string]int {
	r := make(map[string]int, len(keyboard))

	for _, u := range updates {
		for i, key := range u.ids {
			if _, ok := r[key]; !ok {
				r[key] = 0
			}
			r[key] += u.vals[i]
		}
	}

	return r
}

var updates = []update{
	{[]string{"a", "y"}, []int{8, 0}},
	{[]string{"n"}, []int{8}},
	{[]string{"k", "j", "g", "z"}, []int{1, 9, 3, 3}},
	{[]string{"o", "j"}, []int{7, 7}},
	{[]string{"w", "a", "d"}, []int{6, 9, 0}},
	{[]string{"x", "l"}, []int{4, 2}},
	{[]string{"p", "f", "g"}, []int{7, 6, 0}},
	{[]string{"d", "j", "q", "o", "a"}, []int{9, 1, 0, 0, 9}},
	{[]string{"x", "o", "u", "p", "s"}, []int{0, 4, 9, 0, 6}},
	{[]string{"j", "v", "p", "w"}, []int{6, 9, 7, 8}},
	{[]string{"m", "i", "v", "g"}, []int{7, 2, 6, 1}},
	{[]string{"a"}, []int{7}},
	{[]string{"r", "f", "l", "g"}, []int{2, 4, 3, 0}},
	{[]string{"g", "r"}, []int{5, 9}},
	{[]string{"q", "r"}, []int{0, 5}},
	{[]string{"m", "h", "e", "o", "b"}, []int{6, 5, 0, 2, 3}},
	{[]string{"c", "y", "q", "p", "g"}, []int{9, 4, 1, 4, 1}},
	{[]string{"d"}, []int{7}},
	{[]string{"b", "o", "p"}, []int{1, 0, 5}},
	{[]string{"u"}, []int{5}},
	{[]string{"u", "b", "x", "y"}, []int{3, 1, 1, 0}},
	{[]string{"z", "d", "f"}, []int{0, 3, 8}},
	{[]string{"w", "n"}, []int{0, 5}},
	{[]string{"t", "g", "o"}, []int{6, 3, 8}},
	{[]string{"p", "e"}, []int{5, 7}},
	{[]string{"a", "g", "p", "x", "z"}, []int{2, 5, 9, 7, 8}},
	{[]string{"g", "a", "o"}, []int{2, 2, 8}},
	{[]string{"y", "b", "e", "l", "p"}, []int{8, 4, 6, 2, 3}},
	{[]string{"i", "h"}, []int{2, 1}},
	{[]string{"l", "j", "t"}, []int{0, 7, 7}},
	{[]string{"h", "l", "t"}, []int{9, 6, 7}},
	{[]string{"m", "q", "x", "g"}, []int{0, 7, 7, 2}},
	{[]string{"y", "i", "r"}, []int{3, 4, 1}},
	{[]string{"u", "o", "g", "s"}, []int{0, 2, 2, 0}},
	{[]string{"a", "y", "h", "s"}, []int{3, 0, 3, 5}},
	{[]string{"o", "q"}, []int{5, 5}},
	{[]string{"u"}, []int{7}},
	{[]string{"h", "v", "r", "b", "s"}, []int{3, 2, 2, 5, 4}},
	{[]string{"i", "n"}, []int{4, 0}},
	{[]string{"d", "t"}, []int{1, 5}},
	{[]string{"o"}, []int{4}},
	{[]string{"v", "i"}, []int{7, 2}},
	{[]string{"o", "c"}, []int{1, 0}},
	{[]string{"i", "t", "p", "o", "h"}, []int{1, 5, 7, 9, 5}},
	{[]string{"r", "t", "s"}, []int{1, 1, 7}},
	{[]string{"s", "q"}, []int{6, 1}},
	{[]string{"v", "e"}, []int{1, 9}},
	{[]string{"n"}, []int{9}},
	{[]string{"e", "z", "q", "d"}, []int{2, 8, 3, 8}},
	{[]string{"d"}, []int{5}},
	{[]string{"b"}, []int{6}},
	{[]string{"o", "v"}, []int{4, 5}},
	{[]string{"z", "g", "u", "b", "n"}, []int{3, 6, 6, 2, 5}},
	{[]string{"a", "k", "f", "j", "y"}, []int{9, 2, 8, 1, 6}},
	{[]string{"m"}, []int{2}},
	{[]string{"q", "r"}, []int{5, 1}},
	{[]string{"c", "f"}, []int{2, 5}},
	{[]string{"h", "f"}, []int{0, 3}},
	{[]string{"s"}, []int{1}},
	{[]string{"f", "i", "d", "u", "q"}, []int{1, 4, 2, 9, 2}},
	{[]string{"f", "v", "a", "g", "y"}, []int{5, 0, 6, 6, 0}},
	{[]string{"h", "m", "b"}, []int{7, 2, 4}},
	{[]string{"d", "n", "g", "e", "z"}, []int{8, 2, 5, 4, 5}},
	{[]string{"r", "x", "e", "d"}, []int{7, 7, 8, 2}},
	{[]string{"l"}, []int{2}},
	{[]string{"b", "s", "j", "d"}, []int{6, 0, 8, 4}},
	{[]string{"b", "v"}, []int{4, 9}},
	{[]string{"k"}, []int{5}},
	{[]string{"t", "p", "m", "k"}, []int{3, 8, 8, 4}},
	{[]string{"i"}, []int{0}},
	{[]string{"h", "w", "o", "f", "l"}, []int{6, 0, 3, 5, 9}},
	{[]string{"w", "u", "j", "e", "n"}, []int{5, 6, 8, 9, 4}},
	{[]string{"k", "f"}, []int{2, 0}},
	{[]string{"b"}, []int{8}},
	{[]string{"v", "e", "k"}, []int{7, 5, 9}},
	{[]string{"k", "o", "e"}, []int{0, 0, 6}},
	{[]string{"f", "d", "g"}, []int{1, 6, 4}},
	{[]string{"f", "q", "d"}, []int{6, 8, 9}},
	{[]string{"m", "x", "b"}, []int{9, 5, 3}},
	{[]string{"n", "t", "v"}, []int{4, 9, 3}},
	{[]string{"s", "k"}, []int{2, 1}},
	{[]string{"c", "f"}, []int{6, 0}},
	{[]string{"k", "g", "c"}, []int{1, 0, 2}},
	{[]string{"y", "c", "z"}, []int{1, 5, 7}},
	{[]string{"b", "y"}, []int{3, 8}},
	{[]string{"o", "x"}, []int{9, 2}},
	{[]string{"t"}, []int{2}},
	{[]string{"h", "x"}, []int{8, 7}},
	{[]string{"o"}, []int{7}},
	{[]string{"p", "k"}, []int{6, 9}},
	{[]string{"p", "n", "j", "o"}, []int{4, 6, 5, 7}},
	{[]string{"n"}, []int{7}},
	{[]string{"g"}, []int{6}},
	{[]string{"u", "c", "i", "h"}, []int{3, 5, 0, 7}},
	{[]string{"x"}, []int{8}},
	{[]string{"r", "u", "f", "g", "t"}, []int{3, 2, 6, 2, 4}},
	{[]string{"i", "u", "b", "d"}, []int{5, 2, 6, 7}},
	{[]string{"f"}, []int{3}},
	{[]string{"y", "f"}, []int{1, 2}},
	{[]string{"l", "y"}, []int{1, 9}},
}
